name: Deploy Italian App to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your default branch name if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version required by your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Deploy using npm scripts with environment variables
      - name: Deploy
        env:
          CI: false  # Disable treating warnings as errors
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_TEXT_TO_SPEECH_URL: ${{ secrets.REACT_APP_TEXT_TO_SPEECH_URL }}
          REACT_APP_TEXT_TO_SPEECH_XI_API_KEY: ${{ secrets.REACT_APP_TEXT_TO_SPEECH_XI_API_KEY }}
        run: npm run deploy
